### PR TITLE
Update meta balena 5x owa

### PR DESCRIPTION
**Pull request by owzagj**

### CODE REVIEW

**Comment by owzagj** [comment]
@klutchell I just pushed the Rebase button and after it the "Versioned source" failing problem appeared. What is the problem? 
Could help me understand what happened please?

Thanks!

**Comment by klutchell** [comment]
@owzagj Our versioning checks only work with proper rebases from master, not by merging changes from master into your branch. I suggest performing a rebase from origin/master on the command line and force pushing again.

**Comment by floion** [comment]
> @klutchell I just pushed the Rebase button and after it the "Versioned source" failing problem appeared. What is the problem? Could help me understand what happened please?
> 
> Thanks!

When your PR is out of date you have the option in the GitHub UI to update the branch out of which you created the PR. When you do that make sure you click on the arrow next to the `Update branch` button and select the `Update with rebase` option and then click on `Rebase branch`

**Comment by owzagj** [comment]
Nice @floion, this morning a new commit to the master branch brought me the opportunity to test your suggestion and it worked!
Now what is it waiting for? Jenkins build? 

Thanks a lot

**Review by floion — APPROVED** [review]

**Pull request merged**
